// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using USG_Anormaly_Server.Models.db;

#nullable disable

namespace USG_Anormaly_Server.Migrations
{
    [DbContext(typeof(usg_anormaly_mvi_systemContext))]
    partial class usg_anormaly_mvi_systemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("USG_Anormaly_Server.Models.db.TblTrainingModelDetail", b =>
                {
                    b.Property<int>("Item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Item"), 1L, 1);

                    b.Property<bool?>("Activeflag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("activeflag")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("ErrorRemark")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("errorRemark");

                    b.Property<string>("FrontPath")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("frontPath");

                    b.Property<string>("MachineName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("machineName");

                    b.Property<string>("ModelPath")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("modelPath");

                    b.Property<string>("RecipeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("recipeName");

                    b.Property<string>("SidePath1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sidePath1");

                    b.Property<string>("SidePath2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sidePath2");

                    b.Property<DateTime?>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("timeStamp")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("TrainingDate")
                        .HasColumnType("datetime")
                        .HasColumnName("trainingDate");

                    b.Property<DateTime?>("TrainingFinish")
                        .HasColumnType("datetime")
                        .HasColumnName("trainingFinish");

                    b.Property<string>("TrainingParameter")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trainingParameter");

                    b.Property<int?>("TrainingStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("trainingStatus")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Item");

                    b.ToTable("tbl_training_model_detail", (string)null);
                });

            modelBuilder.Entity("USG_Anormaly_Server.Models.db.TblTrainingStatusDetail", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("statusId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"), 1L, 1);

                    b.Property<bool?>("Activeflag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("activeflag")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("StatusDetail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("statusDetail");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updateDate")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("StatusId");

                    b.ToTable("tbl_training_status_detail", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
